billetterie/AdminPanel/urls.py
from django.urls import path
from . import views

app_name = 'nameadmin'
urlpatterns = [
    path('admin/', views.admin, name='admin'),
    path('admin/add_agent/', views.add_agent, name='add_agent'),
    path('admin/ajouter_vehicule/', views.ajouter_vehicule, name='ajouter_vehicule'),
    path('admin/bagage_colis/', views.bagage_colis, name='bagage_colis'),
    path('admin/conf_remise/', views.conf_remise, name='conf_remise'),
    path('admin/conf_trajet/', views.conf_trajet, name='conf_trajet'),
    path('<int:pk>/update_trajet/', views.update_trajet, name='trajet_update'),
    path('<int:pk>/delete_trajet/', views.delete_trajet, name='trajet_delete'),
    path('admin/cree_reservation/', views.cree_reservation, name='cree_reservation'),
    path('admin/cree_destination/', views.cree_destination, name='cree_destination'),
    path('admin/liste_passager/', views.liste_passager, name='liste_passager'),
    path('admin/liste_reservation/', views.liste_reservation, name='liste_reservation'),
    path('admin/recherche_trajet/', views.recherche_trajet, name='recherche_trajet'),
    path('admin/rapport_activite/', views.rapport_activite, name='rapport_activite'),
    path('admin/rapport_agent/', views.rapport_agent, name='rapport_agent'),
]

billetterie/account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('Inscription/', views.Inscription, name='Inscription'),
    path('Connexion', views.Connexion, name='connexion'),
    path('admin/connexion', views.Connexionadmin, name='Connexionadmin'),
    path('logoutUser', views.logoutUser, name='logoutUser'),

]

billetterie/billetterie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('django/', admin.site.urls),
    path('', include('App_billetterie.urls', namespace='appbilletterie')),
    path('', include('AdminPanel.urls', namespace='naneadmin')),
    path('', include('account.urls', namespace='account')),
]

billetterie/AdminPanel/models.py
import datetime
from django.db import models
from account.models import Account

# Create your models here.

class Trajet(models.Model):
    code_trajet = models.CharField(max_length=50)
    lieu_depart = models.CharField(max_length=100, default="")
    lieu_arrivee = models.CharField(max_length=100, default="")
    heure_debut	= models.TimeField()
    heure_fin = models.TimeField()
    prix = models.IntegerField(max_length=100)
    date_enregistrement = models.DateTimeField(auto_now=True)    
    user = models.ForeignKey(Account, on_delete=models.CASCADE, default="")





class Destination(models.Model):
    adresse = models.CharField(max_length=100)
    nom_destination = models.CharField(max_length=100)
    date_enregistrement = models.DateTimeField(auto_now=True)

    user = models.ForeignKey(Account, on_delete=models.CASCADE )




class Vehicule(models.Model):
    immatriculation = models.CharField(max_length=60, default='')
    nom_vehicule = models.CharField(max_length=50, default='')
    capacite = models.IntegerField( default='')
    place_restante = models.IntegerField( default=80,null=True)
    type = models.CharField(max_length=100, default='')
    date_enregistrement = models.DateTimeField(auto_now=True)

    user = models.ForeignKey(Account, on_delete=models.CASCADE, default='')
    trajet = models.ForeignKey(Trajet, on_delete=models.CASCADE, default='')
    
    



class Remise(models.Model):
    code_remise = models.IntegerField(max_length=60)
    date_debut = models.DateField()
    date_fin = models.DateField()
    montant	= models.IntegerField(max_length=100)
    statut_remise = models.BooleanField()
    date_enregistrement = models.DateTimeField(auto_now=True)

    user = models.ForeignKey( Account, on_delete=models.CASCADE)
    trajet = models.OneToOneField( Trajet, on_delete=models.CASCADE)


# class Cycle_trajet(models.Model):
#     date_debut = models.DateField()
#     date_fin = models.DateField()

#     user = models.ForeignKey( Account, on_delete=models.CASCADE)
#     vehicule = models.ForeignKey( Vehicule, on_delete=models.CASCADE)




class Colis(models.Model):
    code_colis = models.CharField(max_length=60)
    trajet = models.ForeignKey(Trajet,on_delete=models.CASCADE, default="")
    status = models.CharField(max_length=100, default="")
    date_depart = models.DateField()
    nom_expediteur	= models.CharField(max_length=100)
    nom_destinataire = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    quantite = models.IntegerField(max_length=100)
    poids = models.IntegerField(max_length=100)
    prix_unitaire = models.IntegerField(max_length=100)
    date_enregistrement = models.DateTimeField(auto_now=True)

    user = models.ForeignKey( Account, on_delete=models.CASCADE) 
    vehicule = models.ForeignKey( Vehicule, on_delete=models.CASCADE)


class Reservations(models.Model):
    #code_reservation = models.CharField(max_length=10,default="",unique=True)
    client = models.ForeignKey(Account,on_delete=models.CASCADE,default="")
    status = models.BooleanField(default=1)
    trajet = models.ForeignKey(Trajet,on_delete=models.CASCADE)
    date_depat = models.DateTimeField()
    heure_depat = models.TimeField(default=datetime.datetime.now())
    place = models.IntegerField(default=1)
    vehicule = models.ForeignKey(Vehicule, on_delete=models.CASCADE, default=1)
    created_at = models.DateTimeField(auto_now=True)

billetterie/AdminPanel/forms.py
from django.forms import ModelForm, TextInput, EmailInput, PasswordInput, NumberInput
from django.contrib.auth.forms import UserCreationForm

from .models import *



class VehiculeForm(ModelForm):
    class Meta:
        model = Vehicule
        fields = ['immatriculation', 'nom_vehicule', 'capacite','type','trajet']


class DestinationForm(ModelForm):
    class Meta:
        model = Destination
        fields = ['adresse', 'nom_destination']

class TrajetForm(ModelForm):
    class Meta:
        model = Trajet
        fields = ['code_trajet', 'lieu_depart','lieu_arrivee','heure_debut','heure_fin','prix']


class RemiseForm(ModelForm):
    class Meta:
        model = Remise
        fields = ['code_remise','date_debut','date_fin','montant','statut_remise', 'trajet']


class ColisForm(ModelForm):
    class Meta:
        model = Colis
        fields = ['code_colis','trajet','date_depart','nom_expediteur','nom_destinataire','status','type','quantite','poids', 'prix_unitaire','vehicule']

class ReservationForm(ModelForm):
    class Meta:
        model = Reservations
        fields = ['trajet', 'date_depat','heure_depat']

billetterie/AdminPanel/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from account.forms import UserCreation
from .forms import *

# Create your views here.
@login_required(login_url="account:Connexionadmin")
def admin(request):
    return render(request, 'adminPanel/admin.html')


@login_required(login_url="account:Connexionadmin")
def add_agent(request):
    agents = Account.objects.filter(is_staff=True)
    form = VehiculeForm()
    if request.method == 'POST':
        form = UserCreation(request.POST)
        if form.is_valid():
            obj = form.save(commit = False)
            obj.is_staff = True
            obj.save()
            messages.info(request, "Information enregistrer avec succes :) ")
    context = {
            'form' : form, 
            'agents':agents,
            'errors' : form.errors.items()
        }
    return render(request, 'adminPanel/dash_html/add_agent.html',context)


@login_required(login_url="account:Connexionadmin")
def ajouter_vehicule(request):

    trajets = Trajet.objects.all()
    vehicules = Vehicule.objects.all()
    form = VehiculeForm()
    if request.method == 'POST':
        form = VehiculeForm(request.POST)
        user =  Account.objects.get(id=request.user.id) 
        if form.is_valid():
            obj = form.save(commit = False)
            obj.user = request.user
            #obj.trajet = Trajet.objects.get(pk=request.trajet)
            obj.save()
            messages.info(request, "Information enregistrer avec succes :) ")
    context = {
            'form' : form, 
            'trajets':trajets,
            'vehicules': vehicules,
            'errors' : form.errors.items()
        }


    return render(request, 'adminPanel/dash_html/ajouter_vehicule.html', context)


@login_required(login_url="account:Connexionadmin")
def bagage_colis(request):

    colis = Colis.objects.all()
    trajets = Trajet.objects.all()
    vehicules = Vehicule.objects.all()
    form = ColisForm()
    if request.method == 'POST':
        form = ColisForm(request.POST)
        user =  Account.objects.get(id=request.user.id) 
        if form.is_valid():
            obj = form.save(commit = False)
            obj.user = request.user
            #obj.trajet = Trajet.objects.get(pk=request.trajet)
            obj.save()
            messages.info(request, "Information enregistrer avec succes :) ")
    context = {
            'form' : form, 
            'trajets':trajets,
            'vehicules': vehicules,
            'colis': colis,
            'errors' : form.errors.items()
        }
    return render(request, 'adminPanel/dash_html/bagage_colis.html',context)


@login_required(login_url="account:Connexionadmin")
def conf_remise(request):
    remise = Remise.objects.all()
    trajets = Trajet.objects.all()
   # vehicules = Vehicule.objects.all()
    form = RemiseForm()
    if request.method == 'POST':
        form = RemiseForm(request.POST)
        user =  Account.objects.get(id=request.user.id) 
        if form.is_valid():
            obj = form.save(commit = False)
            obj.user = request.user
            #obj.trajet = Trajet.objects.get(pk=request.trajet)
            obj.save()
            messages.info(request, "Information enregistrer avec succes :) ")
    context = {
            'form' : form, 
            'trajets':trajets,
            'remises': remise,
            'errors' : form.errors.items()
        }
    return render(request, 'adminPanel/dash_html/conf_remise.html',context)


@login_required(login_url="account:Connexionadmin")
def conf_trajet(request):
    trajets = Trajet.objects.all()
    destinations = Destination.objects.all()
    form = TrajetForm()
    if request.method == 'POST':
        form = TrajetForm(request.POST)
        user =  Account.objects.get(id=request.user.id) 
        if form.is_valid():
            obj = form.save(commit = False)
            obj.user = request.user
            obj.save()
            # obj.user = request.user
            # obj.destination = Destination.objects.get(pk= request.destination)
            # obj.trajet = Trajet.objects.get(pk=request.trajet)
            # obj.save()
            messages.info(request, "Information enregistrer avec succes :) ")
    
    context = {
            'form' : form, 
            'trajets':trajets,
            'destinations':destinations,
            'errors' : form.errors.items()
        }
    

    return render(request, 'adminPanel/dash_html/conf_trajet.html',context)


def update_trajet(request, pk):
    trajet = get_object_or_404(Trajet, pk=pk)
    form = TrajetForm(instance=trajet)
    if request.method == 'PUT':
        form = TrajetForm(request.POST, instance=trajet)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
            messages.info(request, "Informations enregistrées avec succès!")
    context = {
        'form': form,
        'destinations': Destination.objects.all(),
        'trajet': trajet,
        'errors': form.errors.items()
    }
    return render(request, 'adminPanel/dash_html/conf_trajet.html',context)



def delete_trajet(request, pk):
    trajet = get_object_or_404(Trajet, pk=pk)
    if request.method == 'GET':
        trajet.delete()
        messages.info(request, "Trajet supprimé avec succès!")

    return redirect('nameadmin:conf_trajet')



@login_required(login_url="account:Connexionadmin")
def cree_reservation(request):
    trajets = Trajet.objects.all()
    clients = Account.objects.filter(is_admin=False).filter(is_staff=False)
    form = ReservationForm()
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            vehicule = Vehicule.objects.filter(trajet=request.POST.get('trajet'))
          
            place =(int(vehicule[0].capacite) +1)- int(vehicule[0].place_restante)
            update_place_restante =int(vehicule[0].place_restante)-1
            # vehicule[0].place_restante=update_place_restante
            # vehicule[0].save()
            # print((int(vehicule[0].capacite) +1)- int(vehicule[0].place_restante))
            # return HttpResponse([vehicule])
            vehic =Vehicule.objects.get(pk=vehicule[0].pk)
            vehic.place_restante= update_place_restante
            vehic.save()
           
            obj = form.save(commit = False)
            obj.client = request.user
            #obj.vehicule = vehicule
            obj.place = place
            # print(obj)
            # return HttpResponse([vehicule])
            obj.save()
            messages.info(request, "Information enregistrer avec succes :) ")
    context = {
            'form' : form, 
            'trajets':trajets,
            'clients':clients,
            'errors' : form.errors.items()
        }
    return render(request, 'adminPanel/dash_html/cree_reservation.html', context)


@login_required(login_url="account:Connexionadmin")
def cree_destination(request):
    destinations = Destination.objects.all()
    form = DestinationForm()
    if request.method == 'POST':
        form = DestinationForm(request.POST)

        if form.is_valid():
            obj = form.save(commit = False)
            obj.user = request.user
            obj.save()
            messages.info(request, "Information enregistrer avec succes :) ")
    context = {
            'form' : form, 
             'destinations':destinations,
            'errors' : form.errors.items()
        }


    return render(request, 'adminPanel/dash_html/cree_destination.html',context)


@login_required(login_url="account:Connexionadmin")
def rapport_activite(request):
    return render(request, 'adminPanel/dash_html/rapport_activite.html')


@login_required(login_url="account:Connexionadmin")
def rapport_agent(request):
    return render(request, 'adminPanel/dash_html/rapport_agent.html')


@login_required(login_url="account:Connexionadmin")
def liste_passager(request):
    return render(request, 'adminPanel/dash_html/liste_passager.html')


@login_required(login_url="account:Connexionadmin")
def liste_reservation(request):
    trajets = Trajet.objects.all()
    reservations = Reservations.objects.all()
    if request.method == 'POST':
       query = request.POST.get('trajet')
       print(query)
       reservations = Reservations.objects.filter(trajet=query)
    context = {
            'trajets':trajets,
            'reservations':reservations,
        }
    return render(request, 'adminPanel/dash_html/liste_reservation.html',context)


@login_required(login_url="account:Connexionadmin")
def recherche_trajet(request):
    return render(request, 'adminPanel/dash_html/recherche_trajet.html')

billetterie/templates/adminPanel/admin.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8">
    <title> Responsive Admin Dashboard | Transport </title>
    <link rel="stylesheet" href="{% static 'adminPanel/admin.css' %}">
    <link rel="stylesheet" href="{% static 'font/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'font/css/fontawesome.min.css' %}">
    <!-- Boxicons CDN Link -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
    <div class="sidebar">
        <div class="logo-details">
          <i class='bx bx-bus'></i>
          <span class="logo_name">Transport</span>
        </div>
    
    
          <ul class="nav-links">

            <li><a href="#" class="active"><i class='bx bx-grid-alt' ></i><span class="links_name">Dashboard</span></a></li>
            
            <li><a href="{% url 'nameadmin:cree_reservation' %}"><i class='bx bx-box' ></i><span class="links_name">Créer une Commande</span></a></li>
            
            <li><a href="{% url 'nameadmin:recherche_trajet' %}"><i class='bx bx-list-ul' ></i><span class="links_name">Recherche des Trajets</span></a></li>

            <li><a href="{% url 'nameadmin:conf_trajet' %}"><i class='bx bx-cog' ></i><span class="links_name">Config des Trajets</span></a></li>

            <li><a href="{% url 'nameadmin:conf_remise' %}"><i class='bx bx-cog' ></i><span class="links_name">Config des Remises</span></a></li>

            <li><a href="{% url 'nameadmin:cree_destination' %}"><i class='bx bx-current-location'></i><span class="links_name">Créer des Destination</span></a></li>

            <li><a href="{% url 'nameadmin:ajouter_vehicule' %}"><i class='bx bx-car'></i><span class="links_name">Ajouter des Vehicules</span></a></li>

            <li><a href="{% url 'nameadmin:liste_passager' %}"><i class='bx bxs-edit'></i><span class="links_name">Liste des Passagers</span></a></li>

            <li><a href="{% url 'nameadmin:liste_reservation' %}"><i class='bx bx-edit'></i><span class="links_name">Liste des Reservation</span></a></li>

            <li><a href="{% url 'nameadmin:bagage_colis' %}"><i class='bx bxs-shopping-bags'></i><span class="links_name">Bagages et Colis</span></a></li>

            <li  onclick="itemToggle()"><a href="#"><i class='bx bx-stats'></i><span class="links_name">Analyse d'activite</span><i class="bx bx-chevron-down item" onclick="itemToggle()"></i></a>

              <ul id="item">
                <li><a href="{% url 'nameadmin:rapport_activite' %}"><span> Rapport d'activite</span></a></li>
                <li><a href="{% url 'nameadmin:rapport_agent' %}"><span> Rapport Agent</span></a></li>
              </ul>

            </li>
            {% if request.user.is_admin %}
            <li><a href="{% url 'nameadmin:add_agent' %}"><i class='bx bx-user'></i><span class="links_name">Agent</span></a></li>
            {% endif %}
            <li class="log_out"><a href="{% url 'account:logoutUser' %}"><i class='bx bx-log-out'></i><span class="links_name">Log out</span></a></li>
        </ul>
    </div>

    <section class="home-section">
      <nav>
      <div class="sidebar-button">
          <i class='bx bx-menu sidebarBtn'></i>
          <span class="dashboard">Dashboard</span>
      </div>
      <div class="search-box">
          <input type="text" placeholder="Search...">
          <i class='bx bx-search' ></i>
      </div>
      <div class="profile-details">
          <img src="{% static 'images/profile.jpg' %}" alt="">
          <span class="admin_name">Prem Shahi</span>
          <i class='bx bx-chevron-down' ></i>
      </div>
      </nav>

      <div class="home-content">
      <div class="overview-boxes">
          <div class="box">
          <div class="right-side">
              <div class="box-topic">Total Order</div>
              <div class="number">40,876</div>
              <div class="indicator">
              <i class='bx bx-up-arrow-alt'></i>
              <span class="text">Up from yesterday</span>
              </div>
          </div>
          <i class='bx bx-cart-alt cart'></i>
          </div>
          <div class="box">
          <div class="right-side">
              <div class="box-topic">Total Sales</div>
              <div class="number">38,876</div>
              <div class="indicator">
              <i class='bx bx-up-arrow-alt'></i>
              <span class="text">Up from yesterday</span>
              </div>
          </div>
          <i class='bx bxs-cart-add cart two' ></i>
          </div>
          <div class="box">
          <div class="right-side">
              <div class="box-topic">Total Profit</div>
              <div class="number">$12,876</div>
              <div class="indicator">
              <i class='bx bx-up-arrow-alt'></i>
              <span class="text">Up from yesterday</span>
              </div>
          </div>
          <i class='bx bx-cart cart three' ></i>
          </div>
          <div class="box">
          <div class="right-side">
              <div class="box-topic">Total Return</div>
              <div class="number">11,086</div>
              <div class="indicator">
              <i class='bx bx-down-arrow-alt down'></i>
              <span class="text">Down From Today</span>
              </div>
          </div>
          <i class='bx bxs-cart-download cart four' ></i>
          </div>
      </div>

      <div class="sales-boxes">
          <div class="recent-sales box">
          <div class="title">Recent Sales</div>
          <div class="sales-details">
              <ul class="details">
              <li class="topic">Date</li>
              <li><a href="#">02 Jan 2021</a></li>
              <li><a href="#">02 Jan 2021</a></li>
              <li><a href="#">02 Jan 2021</a></li>
              <li><a href="#">02 Jan 2021</a></li>
              <li><a href="#">02 Jan 2021</a></li>
              <li><a href="#">02 Jan 2021</a></li>
              <li><a href="#">02 Jan 2021</a></li>
              </ul>
              <ul class="details">
              <li class="topic">Customer</li>
              <li><a href="#">Alex Doe</a></li>
              <li><a href="#">David Mart</a></li>
              <li><a href="#">Roe Parter</a></li>
              <li><a href="#">Diana Penty</a></li>
              <li><a href="#">Martin Paw</a></li>
              <li><a href="#">Doe Alex</a></li>
              <li><a href="#">Aiana Lexa</a></li>
              <li><a href="#">Rexel Mags</a></li>
              <li><a href="#">Tiana Loths</a></li>
          </ul>
          <ul class="details">
              <li class="topic">Sales</li>
              <li><a href="#">Delivered</a></li>
              <li><a href="#">Pending</a></li>
              <li><a href="#">Returned</a></li>
              <li><a href="#">Delivered</a></li>
              <li><a href="#">Pending</a></li>
              <li><a href="#">Returned</a></li>
              <li><a href="#">Delivered</a></li>
              <li><a href="#">Pending</a></li>
              <li><a href="#">Delivered</a></li>
          </ul>
          <ul class="details">
              <li class="topic">Total</li>
              <li><a href="#">$204.98</a></li>
              <li><a href="#">$24.55</a></li>
              <li><a href="#">$25.88</a></li>
              <li><a href="#">$170.66</a></li>
              <li><a href="#">$56.56</a></li>
              <li><a href="#">$44.95</a></li>
              <li><a href="#">$67.33</a></li>
              <li><a href="#">$23.53</a></li>
              <li><a href="#">$46.52</a></li>
          </ul>
          </div>
          <div class="button">
              <a href="#">See All</a>
          </div>
          </div>
          <div class="top-sales box">
              <div class="title">Top Seling Product</div>
                  <ul class="top-sales-details">
                      <li>
                          <a href="#">
                          <img src="{% static 'images/log.svg' %}" alt="">
                          <span class="product">Vuitton Sunglasses</span>
                          </a>
                          <span class="price">$1107</span>
                      </li>
                      <li>
                          <a href="#">
                          <img src="{% static 'images/jeans.jpg' %}" alt="">
                          <span class="product">Hourglass Jeans </span>
                          </a>
                          <span class="price">$1567</span>
                      </li>
                      <li>
                          <a href="#">
                          <img src="{% static 'images/nike.jpg' %}" alt="">
                          <span class="product">Nike Sport Shoe</span>
                          </a>
                          <span class="price">$1234</span>
                      </li>
                      <li>
                          <a href="#">
                          <img src="{% static 'images/scarves.jpg' %}" alt="">
                          <span class="product">Hermes Silk Scarves.</span>
                          </a>
                          <span class="price">$2312</span>
                      </li>
                      <li>
                          <a href="#">
                          <img src="{% static 'images/blueBag.jpg' %}" alt="">
                          <span class="product">Succi Ladies Bag</span>
                          </a>
                      <span class="price">$1456</span>
                      </li>
                      <li>
                          <a href="#">
                          <img src="{% static 'images/bag.jpg' %}" alt="">
                          <span class="product">Gucci Womens's Bags</span>
                          </a>
                          <span class="price">$2345</span>
                      </li>
                      <li>
                          <a href="#">
                          <img src="{% static 'images/addidas.jpg' %}" alt="">
                          <span class="product">Addidas Running Shoe</span>
                          </a>
                          <span class="price">$2345</span>
                      </li>
                      <li>
                          <a href="#">
                          <img src="{% static 'images/shirt.jpg' %}" alt="">
                          <span class="product">Bilack Wear's Shirt</span>
                          </a>
                          <span class="price">$1245</span>
                      </li>
                  </ul>
              </div>
          </div>
      </div>
  </section>
  <script>

    const item = document.getElementById('item');

    function itemToggle(){
      item.classList.toggle('active');
    }


  </script>
  <script src="{% static 'adminPanel/dash_js/admin.js' %}"></script>
</body>
</html>