billetterie/AdminPanel/urls.py
from django.urls import path
from . import views

app_name = 'nameadmin'
urlpatterns = [
    path('admin/', views.admin, name='admin'),
    path('admin/add_agent/', views.add_agent, name='add_agent'),
    path('admin/ajouter_vehicule/', views.ajouter_vehicule, name='ajouter_vehicule'),
    path('admin/bagage_colis/', views.bagage_colis, name='bagage_colis'),
    path('admin/conf_remise/', views.conf_remise, name='conf_remise'),
    path('admin/conf_trajet/', views.conf_trajet, name='conf_trajet'),
    path('<int:pk>/update_trajet/', views.update_trajet, name='trajet_update'),
    path('<int:pk>/delete_trajet/', views.delete_trajet, name='trajet_delete'),
    path('admin/cree_reservation/', views.cree_reservation, name='cree_reservation'),
    path('admin/cree_destination/', views.cree_destination, name='cree_destination'),
    path('admin/liste_passager/', views.liste_passager, name='liste_passager'),
    path('admin/liste_reservation/', views.liste_reservation, name='liste_reservation'),
    path('admin/recherche_trajet/', views.recherche_trajet, name='recherche_trajet'),
    path('admin/rapport_activite/', views.rapport_activite, name='rapport_activite'),
    path('admin/rapport_agent/', views.rapport_agent, name='rapport_agent'),
]

billetterie/App_billetterie/urls.py
from django.urls import path
from . import views

app_name = 'appbilletterie'
urlpatterns = [
    path('', views.index, name='index'),
    path('reservation/', views.reservation, name='reservation'),
    path('search/', views.search, name='search'),
    path('paiement/', views.paiement, name='paiement'),
    path('valider_paiement/', views.valider_paiement, name='valider_paiement'),


    path('agent/', views.agent, name='agent'),
    path('liste_commande/', views.liste_commande, name='liste_commande'),
    path('bagage_colis1/', views.bagage_colis1, name='bagage_colis1'),
    path('cree_commande/', views.cree_commande, name='cree_commande'),
    path('recherche_trajet1/', views.recherche_trajet1, name='recherche_trajet1'),

]

billetterie/account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('Inscription/', views.Inscription, name='Inscription'),
    path('Connexion', views.Connexion, name='connexion'),
    path('admin/connexion', views.Connexionadmin, name='Connexionadmin'),
    path('logoutUser', views.logoutUser, name='logoutUser'),

]

billetterie/billetterie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('django/', admin.site.urls),
    path('', include('App_billetterie.urls', namespace='appbilletterie')),
    path('', include('AdminPanel.urls', namespace='naneadmin')),
    path('', include('account.urls', namespace='account')),
]

billetterie/AdminPanel/models.py
import datetime
from django.db import models
from account.models import Account

# Create your models here.

class Trajet(models.Model):
    code_trajet = models.CharField(max_length=50)
    lieu_depart = models.CharField(max_length=100, default="")
    lieu_arrivee = models.CharField(max_length=100, default="")
    heure_debut	= models.TimeField()
    heure_fin = models.TimeField()
    prix = models.IntegerField(max_length=100)
    date_enregistrement = models.DateTimeField(auto_now=True)    
    user = models.ForeignKey(Account, on_delete=models.CASCADE, default="")





class Destination(models.Model):
    adresse = models.CharField(max_length=100)
    nom_destination = models.CharField(max_length=100)
    date_enregistrement = models.DateTimeField(auto_now=True)

    user = models.ForeignKey(Account, on_delete=models.CASCADE )




class Vehicule(models.Model):
    immatriculation = models.CharField(max_length=60, default='')
    nom_vehicule = models.CharField(max_length=50, default='')
    capacite = models.IntegerField( default='')
    place_restante = models.IntegerField( default=80,null=True)
    type = models.CharField(max_length=100, default='')
    date_enregistrement = models.DateTimeField(auto_now=True)

    user = models.ForeignKey(Account, on_delete=models.CASCADE, default='')
    trajet = models.ForeignKey(Trajet, on_delete=models.CASCADE, default='')
    
    



class Remise(models.Model):
    code_remise = models.IntegerField(max_length=60)
    date_debut = models.DateField()
    date_fin = models.DateField()
    montant	= models.IntegerField(max_length=100)
    statut_remise = models.BooleanField()
    date_enregistrement = models.DateTimeField(auto_now=True)

    user = models.ForeignKey( Account, on_delete=models.CASCADE)
    trajet = models.OneToOneField( Trajet, on_delete=models.CASCADE)


# class Cycle_trajet(models.Model):
#     date_debut = models.DateField()
#     date_fin = models.DateField()

#     user = models.ForeignKey( Account, on_delete=models.CASCADE)
#     vehicule = models.ForeignKey( Vehicule, on_delete=models.CASCADE)




class Colis(models.Model):
    code_colis = models.CharField(max_length=60)
    trajet = models.ForeignKey(Trajet,on_delete=models.CASCADE, default="")
    status = models.CharField(max_length=100, default="")
    date_depart = models.DateField()
    nom_expediteur	= models.CharField(max_length=100)
    nom_destinataire = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    quantite = models.IntegerField(max_length=100)
    poids = models.IntegerField(max_length=100)
    prix_unitaire = models.IntegerField(max_length=100)
    date_enregistrement = models.DateTimeField(auto_now=True)

    user = models.ForeignKey( Account, on_delete=models.CASCADE) 
    vehicule = models.ForeignKey( Vehicule, on_delete=models.CASCADE)


class Reservations(models.Model):
    #code_reservation = models.CharField(max_length=10,default="",unique=True)
    client = models.ForeignKey(Account,on_delete=models.CASCADE,default="")
    status = models.BooleanField(default=1)
    trajet = models.ForeignKey(Trajet,on_delete=models.CASCADE)
    date_depat = models.DateTimeField()
    heure_depat = models.TimeField(default=datetime.datetime.now())
    place = models.IntegerField(default=1)
    vehicule = models.ForeignKey(Vehicule, on_delete=models.CASCADE, default=1)
    created_at = models.DateTimeField(auto_now=True)

billetterie/AdminPanel/forms.py
from django.forms import ModelForm, TextInput, EmailInput, PasswordInput, NumberInput
from django.contrib.auth.forms import UserCreationForm

from .models import *



class VehiculeForm(ModelForm):
    class Meta:
        model = Vehicule
        fields = ['immatriculation', 'nom_vehicule', 'capacite','type','trajet']


class DestinationForm(ModelForm):
    class Meta:
        model = Destination
        fields = ['adresse', 'nom_destination']

class TrajetForm(ModelForm):
    class Meta:
        model = Trajet
        fields = ['code_trajet', 'lieu_depart','lieu_arrivee','heure_debut','heure_fin','prix']


class RemiseForm(ModelForm):
    class Meta:
        model = Remise
        fields = ['code_remise','date_debut','date_fin','montant','statut_remise', 'trajet']


class ColisForm(ModelForm):
    class Meta:
        model = Colis
        fields = ['code_colis','trajet','date_depart','nom_expediteur','nom_destinataire','status','type','quantite','poids', 'prix_unitaire','vehicule']

class ReservationForm(ModelForm):
    class Meta:
        model = Reservations
        fields = ['trajet', 'date_depat','heure_depat']

billetterie/AdminPanel/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from account.forms import UserCreation
from .forms import *

# Create your views here.
@login_required(login_url="account:Connexionadmin")
def admin(request):
    return render(request, 'adminPanel/admin.html')


@login_required(login_url="account:Connexionadmin")
def add_agent(request):
    agents = Account.objects.filter(is_staff=True)
    form = VehiculeForm()
    if request.method == 'POST':
        form = UserCreation(request.POST)
        if form.is_valid():
            obj = form.save(commit = False)
            obj.is_staff = True
            obj.save()
            messages.info(request, "Information enregistrer avec succes :) ")
    context = {
            'form' : form, 
            'agents':agents,
            'errors' : form.errors.items()
        }
    return render(request, 'adminPanel/dash_html/add_agent.html',context)


@login_required(login_url="account:Connexionadmin")
def ajouter_vehicule(request):

    trajets = Trajet.objects.all()
    vehicules = Vehicule.objects.all()
    form = VehiculeForm()
    if request.method == 'POST':
        form = VehiculeForm(request.POST)
        user =  Account.objects.get(id=request.user.id) 
        if form.is_valid():
            obj = form.save(commit = False)
            obj.user = request.user
            #obj.trajet = Trajet.objects.get(pk=request.trajet)
            obj.save()
            messages.info(request, "Information enregistrer avec succes :) ")
    context = {
            'form' : form, 
            'trajets':trajets,
            'vehicules': vehicules,
            'errors' : form.errors.items()
        }


    return render(request, 'adminPanel/dash_html/ajouter_vehicule.html', context)


@login_required(login_url="account:Connexionadmin")
def bagage_colis(request):

    colis = Colis.objects.all()
    trajets = Trajet.objects.all()
    vehicules = Vehicule.objects.all()
    form = ColisForm()
    if request.method == 'POST':
        form = ColisForm(request.POST)
        user =  Account.objects.get(id=request.user.id) 
        if form.is_valid():
            obj = form.save(commit = False)
            obj.user = request.user
            #obj.trajet = Trajet.objects.get(pk=request.trajet)
            obj.save()
            messages.info(request, "Information enregistrer avec succes :) ")
    context = {
            'form' : form, 
            'trajets':trajets,
            'vehicules': vehicules,
            'colis': colis,
            'errors' : form.errors.items()
        }
    return render(request, 'adminPanel/dash_html/bagage_colis.html',context)


@login_required(login_url="account:Connexionadmin")
def conf_remise(request):
    remise = Remise.objects.all()
    trajets = Trajet.objects.all()
   # vehicules = Vehicule.objects.all()
    form = RemiseForm()
    if request.method == 'POST':
        form = RemiseForm(request.POST)
        user =  Account.objects.get(id=request.user.id) 
        if form.is_valid():
            obj = form.save(commit = False)
            obj.user = request.user
            #obj.trajet = Trajet.objects.get(pk=request.trajet)
            obj.save()
            messages.info(request, "Information enregistrer avec succes :) ")
    context = {
            'form' : form, 
            'trajets':trajets,
            'remises': remise,
            'errors' : form.errors.items()
        }
    return render(request, 'adminPanel/dash_html/conf_remise.html',context)


@login_required(login_url="account:Connexionadmin")
def conf_trajet(request):
    trajets = Trajet.objects.all()
    destinations = Destination.objects.all()
    form = TrajetForm()
    if request.method == 'POST':
        form = TrajetForm(request.POST)
        user =  Account.objects.get(id=request.user.id) 
        if form.is_valid():
            obj = form.save(commit = False)
            obj.user = request.user
            obj.save()
            # obj.user = request.user
            # obj.destination = Destination.objects.get(pk= request.destination)
            # obj.trajet = Trajet.objects.get(pk=request.trajet)
            # obj.save()
            messages.info(request, "Information enregistrer avec succes :) ")
    
    context = {
            'form' : form, 
            'trajets':trajets,
            'destinations':destinations,
            'errors' : form.errors.items()
        }
    

    return render(request, 'adminPanel/dash_html/conf_trajet.html',context)


def update_trajet(request, pk):
    trajet = get_object_or_404(Trajet, pk=pk)
    form = TrajetForm(instance=trajet)
    if request.method == 'PUT':
        form = TrajetForm(request.POST, instance=trajet)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
            messages.info(request, "Informations enregistrées avec succès!")
    context = {
        'form': form,
        'destinations': Destination.objects.all(),
        'trajet': trajet,
        'errors': form.errors.items()
    }
    return render(request, 'adminPanel/dash_html/conf_trajet.html',context)



def delete_trajet(request, pk):
    trajet = get_object_or_404(Trajet, pk=pk)
    if request.method == 'GET':
        trajet.delete()
        messages.info(request, "Trajet supprimé avec succès!")

    return redirect('nameadmin:conf_trajet')



@login_required(login_url="account:Connexionadmin")
def cree_reservation(request):
    trajets = Trajet.objects.all()
    clients = Account.objects.filter(is_admin=False).filter(is_staff=False)
    form = ReservationForm()
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            vehicule = Vehicule.objects.filter(trajet=request.POST.get('trajet'))
          
            place =(int(vehicule[0].capacite) +1)- int(vehicule[0].place_restante)
            update_place_restante =int(vehicule[0].place_restante)-1
            # vehicule[0].place_restante=update_place_restante
            # vehicule[0].save()
            # print((int(vehicule[0].capacite) +1)- int(vehicule[0].place_restante))
            # return HttpResponse([vehicule])
            vehic =Vehicule.objects.get(pk=vehicule[0].pk)
            vehic.place_restante= update_place_restante
            vehic.save()
           
            obj = form.save(commit = False)
            obj.client = request.user
            #obj.vehicule = vehicule
            obj.place = place
            # print(obj)
            # return HttpResponse([vehicule])
            obj.save()
            messages.info(request, "Information enregistrer avec succes :) ")
    context = {
            'form' : form, 
            'trajets':trajets,
            'clients':clients,
            'errors' : form.errors.items()
        }
    return render(request, 'adminPanel/dash_html/cree_reservation.html', context)


@login_required(login_url="account:Connexionadmin")
def cree_destination(request):
    destinations = Destination.objects.all()
    form = DestinationForm()
    if request.method == 'POST':
        form = DestinationForm(request.POST)

        if form.is_valid():
            obj = form.save(commit = False)
            obj.user = request.user
            obj.save()
            messages.info(request, "Information enregistrer avec succes :) ")
    context = {
            'form' : form, 
             'destinations':destinations,
            'errors' : form.errors.items()
        }


    return render(request, 'adminPanel/dash_html/cree_destination.html',context)


@login_required(login_url="account:Connexionadmin")
def rapport_activite(request):
    return render(request, 'adminPanel/dash_html/rapport_activite.html')


@login_required(login_url="account:Connexionadmin")
def rapport_agent(request):
    return render(request, 'adminPanel/dash_html/rapport_agent.html')


@login_required(login_url="account:Connexionadmin")
def liste_passager(request):
    return render(request, 'adminPanel/dash_html/liste_passager.html')


@login_required(login_url="account:Connexionadmin")
def liste_reservation(request):
    trajets = Trajet.objects.all()
    reservations = Reservations.objects.all()
    if request.method == 'POST':
       query = request.POST.get('trajet')
       print(query)
       reservations = Reservations.objects.filter(trajet=query)
    context = {
            'trajets':trajets,
            'reservations':reservations,
        }
    return render(request, 'adminPanel/dash_html/liste_reservation.html',context)


@login_required(login_url="account:Connexionadmin")
def recherche_trajet(request):
    return render(request, 'adminPanel/dash_html/recherche_trajet.html')

billetterie/templates/adminPanel/dash_html/conf_trajet.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Configuration Trajet</title>
    <link rel="stylesheet" href="{% static 'font/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'font/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminPanel/dash_css/gestion.css' %}">
</head>
<body>
    <div class="table">
        <div class="table_header">
            <p>Configuration des Trajets</p>
            <div>
                <button class="add_new button" onclick="popupToggle();">+ Create Trajet</button>
            </div>
        </div>
        <div class="table_section">
            <table>
                <thead>
                    <tr>
                        <th>No</th>
                        <th>lieu_depart</th>
                        <th>lieu_arrivee</th>
                        <!-- <th>Vehicule(s)</th> -->
                        <th>Heure</th>
                        <th>Prix</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <!-- <tbody>
                    <tr>
                        <td>Abidjan - Abengourou</td>
                        <td>HDMI</td>
                        <td>16 places</td>
                        <td>7h30 - 22h30</td>
                        <td>20$</td>
                        <td>
                            <button><i class="fas fa-pen-square" onclick="popupToggleEdit();"></i></button>
                            <button><i class="fas fa-trash"></i></button>
                        </td>
                    </tr>
                </tbody> -->

                <tbody>
                    {% for  trajet in trajets %}
             
                  
                    <tr>
                        <td>{{trajet.code_trajet}}</td>
                        <td>{{trajet.lieu_depart}}</td>
                        <td>{{trajet.lieu_arrivee}}</td>
                        <td>{{trajet.heure_debut}}</td>
                        <td>{{trajet.prix}}</td>
                        <td>
                            <button><i class="fas fa-pen-square" onclick="popupToggleEdit();"></i></button>
                            <button><i class="fas fa-trash"></i><a href="{% url 'nameadmin:trajet_delete' trajet.id %}" >suprier</a>
                            </button>
                        </td>
                    </tr>
                    {%endfor%}
                </tbody>
            </table>
        </div>
        <!-- <div class="pagination">
            <div><i class="fas fa-angle-double-left"></i></div>
            <div><i class="fas fa-chevron-left"></i></div>
            <div>1</div>
            <div>2</div>
            <div><i class="fas fa-chevron-right"></i></div>
            <div><i class="fas fa-angle-double-right"></i></div>
        </div> -->
    </div>
    <div id="popup">
        <div class="content">
            <h2>Créer un trajet</h2>
            <hr>
            <form action="" method="POST">
                {% if errors %}
                <div>
                    {% for error in errors %}
                    <p>{{error}}</p>
                    {%endfor%}
                </div>
                {%endif%}

                {% csrf_token %}
                <p>#No</p>
                <!-- <input type="text" name="#" placeholder="HNDN"> -->
                {{form.code_trajet}}
                <div class="lieu">
                    <div class="lieu1">
                        <p>Depart</p>
                        <select name="lieu_depart" required>
                            <!-- <option selected disabled>Ville de Départ</option> -->
                            {% for  destination in destinations %}
                            <option value="{{destination.adresse}}">  {{destination.adresse}}</option>
                              {%endfor%}
                        </select> 
                    </div>
                    <div class="lieu1">
                        <p>Arrivé</p>
                        <select name="lieu_arrivee" required>
                            {% for  destination in destinations %}
                            <option value="{{destination.adresse}}">  {{destination.adresse}}</option>
                              {%endfor%}
                        </select> 
                    </div>
                </div>
                <div class="heure">
                    <div class="heure_debut">
                        <p>Heure de debut</p>
                        <!-- {{form.heure_debut}} -->
                         <input type="time" name="heure_debut" placeholder="Heure:Minute (07:30)"> 
                    </div>
                    <div class="heure_fin">
                        <p>Heure de fin</p>
                        <!-- {{form.heure_fin}} -->
                         <input type="time" name="heure_fin" placeholder="Heure:Minute (22:30)">
                    </div>
                </div>
                <div class="voiture_prix">
                    <!-- <div class="voiture_prix1">
                        <p>capaciter vehicule</p>
                        <input type="number" name="#">
                    </div> -->
                    <div class="voiture_prix1">
                        <p>Prix</p>
                        <!-- <input type="number" name="prix"> -->
                        {{form.prix}}
                    </div>
                </div>
                <div class="inputBox">
                    <input type="submit" value="Save">
                </div> 
               
            </form>
        </div>
        <a class="fas fa-times close" onclick="popupToggle();"></a>
    </div>

    <!-- Update or Edit popup -->

    <div id="popupedit">
        <div class="content">
            <h2>Modifié le trajet</h2>
            <hr>
            <form action="" method="POST">
                {% if errors %}
                <div>
                    {% for error in errors %}
                    <p>{{error}}</p>
                    {%endfor%}
                </div>
                {%endif%}

                {% csrf_token %}
                <p>#No</p>
                <!-- <input type="text" name="#" placeholder="HNDN"> -->
                {{form.code_trajet}}
                <div class="lieu">
                    <div class="lieu1">
                        <p>Depart</p>
                        <select name="lieu_depart" required>
                            <!-- <option selected disabled>Ville de Départ</option> -->
                            {% for  destination in destinations %}
                            <option value="{{destination.adresse}}">  {{destination.adresse}}</option>
                              {%endfor%}
                        </select> 
                    </div>
                    <div class="lieu1">
                        <p>Arrivé</p>
                        <select name="lieu_arrivee" required>
                            {% for  destination in destinations %}
                            <option value="{{destination.adresse}}">  {{destination.adresse}}</option>
                              {%endfor%}
                        </select> 
                    </div>
                </div>
                <div class="heure">
                    <div class="heure_debut">
                        <p>Heure de debut</p>
                        <!-- {{form.heure_debut}} -->
                         <input type="time" name="heure_debut" placeholder="Heure:Minute (07:30)" value="{{trajet.heure_debut}}"> 
                    </div>
                    <div class="heure_fin">
                        <p>Heure de fin</p>
                        <!-- {{form.heure_fin}} -->
                         <input type="time" name="heure_fin" placeholder="Heure:Minute (22:30)">
                    </div>
                </div>
                <div class="voiture_prix">
                    <!-- <div class="voiture_prix1">
                        <p>capaciter vehicule</p>
                        <input type="number" name="#">
                    </div> -->
                    <div class="voiture_prix1">
                        <p>Prix</p>
                        <input type="number" name="prix" value="{{trajet.prix}}">
                        <!-- {{form.prix}} -->
                    </div>
                </div>
                <div class="inputBox">
                    <input type="submit" value="Save">
                </div> 
               
            </form>
        </div>
        <a class="fas fa-times close" onclick="popupToggleEdit();"></a>
    </div>

    <script>
      function delete_trajet(url) {
       console.log('fzefze')
    if (confirm('Êtes-vous sûr de vouloir supprimer ce trajet ?')) {
        window.location.href = url;
    }
}

    </script>
    <script src="{% static 'adminPanel/dash_js/gestion.js' %}"></script>
</body>
</html>

billetterie/templates/adminPanel/dash_html/cree_reservation.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crée une Commande</title>
    <link rel="stylesheet" href="{% static 'font/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'font/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminPanel/dash_css/gestion.css' %}">
</head>
<body>
    <div id="popup" style="left: 50%; visibility: visible;">
        <div class="content">
            <h2>Créer une Commande</h2>
            {% for message in messages %}
            <p class="bg-info">{{message}}</p>
            {%endfor%}
            <hr>
            <form action="" method="post">
                <div>
                    {% for  error in errors %}
                    {{error}}
                    {%endfor%}
                </div>
                {% csrf_token %}
                <!-- <p>Sejour</p>
                <input type="text" name="#" placeholder="Allez simple ou Allé-retour"> -->
                <div class="lieu">
                    <div class="lieu1">
                        <p>Trajet</p>
                       
                        <select name="trajet" required>
                            {% for trajet in trajets %}
                            <option value="{{trajet.id}}">  {{trajet.lieu_depart}}- {{trajet.lieu_arrivee}}</option>
                              {%endfor%}
                            <option value="korhogo">Korhogo</option>
                        </select> 
                    </div>
                    <div class="lieu1">
                        <p>Client</p>
                        <select name="#" required>
                            {% for client in clients %}
                        <option value="{{client.id}}">{{client.username}} </option>
                          {%endfor%}
                        </select> 
                    </div>
                </div>
                <div class="heure">
                    <div class="heure1">
                        <p>Date de Depart</p>
                        <input type="date" name="date_depat">
                    </div>
                    <!-- <div class="heure1">
                        <p>Date de Retour</p>
                        <input type="date" name="#">
                    </div> -->
                </div>
                <div class="voiture_prix">
                    <!-- <div class="voiture_prix1">
                        <p>Passagers</p>
                        <input type="number" name="#" placeholder="nombre de Passager">
                    </div> -->
                    <div class="voiture_prix1">
                        <p>Heure de Depart</p>
                        <input type="time" name="heure_depat">
                    </div>
                </div>
                <button type="submit" class="add_new button"></i>Reserver</button> 
               
                <!-- <button class="add_new button"><i class="fas fa-search"></i><a href="{% url 'appbilletterie:search' %}" style="color: #fff; padding: 13px 5px;"> Recherche</a></button> -->
            </form>
        </div>
    </div>
    <script src="{% static 'adminPanel/dash_js/gestion.js' %}"></script>
</body>
</html>