billetterie/App_billetterie/urls.py
from django.urls import path
from . import views

app_name = 'appbilletterie'
urlpatterns = [
    path('', views.index, name='index'),
    path('reservation/', views.reservation, name='reservation'),
    path('search/', views.search, name='search'),
    path('paiement/', views.paiement, name='paiement'),
    path('valider_paiement/', views.valider_paiement, name='valider_paiement'),


    path('agent/', views.agent, name='agent'),
    path('liste_commande/', views.liste_commande, name='liste_commande'),
    path('bagage_colis1/', views.bagage_colis1, name='bagage_colis1'),
    path('cree_commande/', views.cree_commande, name='cree_commande'),
    path('recherche_trajet1/', views.recherche_trajet1, name='recherche_trajet1'),

]

billetterie/account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('Inscription/', views.Inscription, name='Inscription'),
    path('Connexion', views.Connexion, name='connexion'),
    path('admin/connexion', views.Connexionadmin, name='Connexionadmin'),
    path('logoutUser', views.logoutUser, name='logoutUser'),

]

billetterie/billetterie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('django/', admin.site.urls),
    path('', include('App_billetterie.urls', namespace='appbilletterie')),
    path('', include('AdminPanel.urls', namespace='naneadmin')),
    path('', include('account.urls', namespace='account')),
]

billetterie/templates/htmlPages/connexion.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'font/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'font/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'cssPages/swiper-bundle.min.css' %}">
    <link rel="stylesheet" href="{% static 'cssPages/connexion.css' %}">
    <title>Inscription & Connexion</title>
  </head>
  <body>
    <div class="container">
      <div class="forms-container">
        <div class="signin-signup">
          
          <form action="" method="post" class="sign-in-form">
                {% csrf_token %}
            <h2 class="title">Se Connecter</h2>
            <div class="input-field">
              <i class="fas fa-user"></i>
              <input type="text" placeholder="Username" name="username"/>
            </div>
            <div class="input-field">
              <i class="fas fa-lock"></i>
              <input type="password" placeholder="" name="password"/>
            </div>
            <input type="submit" value="Connexion" class="btn solid" />
            <p class="social-text">Connecter-vous les plateformes sociales</p>
            <div class="social-media">
              <a href="#" class="social-icon">
                <i class="fab fa-facebook-f"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-twitter"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-google"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </div>
          </form>
          {% for message in messages %}
          <p>{{message}}</p>
          {%endfor%}

          <form action="{%url 'account:Inscription' %}" method="post" class="sign-up-form">
            <div>
              {% for  error in errors %}
              {{error}}
              {%endfor%}
          </div>
            {% csrf_token %}
            <h2 class="title">S'Inscrire</h2>
            <div class="input-field">
              <i class="fas fa-user"></i>
              <input type="text" placeholder="Username" name="username" />
            </div>
            <div class="input-field">
              <i class="fas fa-envelope"></i>
              <input type="email" placeholder="Email" name="email" />
            </div>
            <div class="input-field">
              <i class="fas fa-envelope"></i>
              <input type="text" placeholder="Phone" name="phone" />
            </div>
            <div class="input-field">
              <i class="fas fa-lock"></i>
              <input type="password" placeholder="Password" name="password1"/>
            </div>
            <div class="input-field">
              <i class="fas fa-lock"></i>
              <input type="password" placeholder="Password" name="password2"/>
            </div>
            <input type="submit" class="btn" value="Inscription" />
            <p class="social-text">Inscrivez-vous les plateformes sociales</p>
            <div class="social-media">
              <a href="#" class="social-icon">
                <i class="fab fa-facebook-f"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-twitter"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-google"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </div>
          </form>
        </div>
      </div>

      <div class="panels-container">

        <div class="panel left-panel">
          <div class="content">
            <h3>New here ?</h3>
            <p>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis,
              ex ratione. Aliquid!
            </p>
            <button class="btn transparent" id="sign-up-btn">
              Inscription
            </button>
          </div>
          <img src="{% static 'images/log.svg' %}" class="image" alt="" />
        </div>

        <div class="panel right-panel">
          <div class="content">
            <h3>One of us ?</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum
              laboriosam ad deleniti.
            </p>
            <button class="btn transparent" id="sign-in-btn">
              Connexion
            </button>
          </div>
          <img src="{% static 'images/register.svg' %}" class="image" alt="" />
        </div>

      </div>
    </div>

    <script src="{% static 'javaScript/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'javaScript/connexion.js' %}"></script>
  </body>
</html>

billetterie/templates/htmlPages/paiement.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Paiement</title>
    <link rel="stylesheet" href="{% static 'cssPages/search.css' %}">
    <link rel="stylesheet" href="{% static 'font/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'font/css/fontawesome.min.css' %}">
</head>
<body>
    <div class="table">
        <div class="table_header">
            <p>Numero reservation</p>
            <div>
                <a href="#"><button class="add_new button" onclick="popupToggle();"> Effectuer le paiement</button></a>
                <button class="add_new button"><i class="fas fa-chevron-left"></i><a href="{% url 'appbilletterie:search' %}"> Retour</a></button>
            </div>
            
        </div>
        <hr>
    </div>
    <div class="codeqr">

    </div>
    <div class="info-trajet">
        <div class="infos">
            <div class="info">
                <p>Statut</p>
                <p>En attente</p>
            </div>
            <div class="info">
                <p>Statut</p>
                <p>Non Réglé</p>
            </div>
        </div>
        <div class="information">
            <div class="info">
                <p>Nom Complet</p>
                <p>Elisee Koffi</p>
            </div>
            <div class="info">
                <p>Téléphone</p>
                <p>0025 0700000000</p>
            </div>
        </div>
        <div class="trajets">
            <div class="trajet">
                <p>Lieu de départ</p>
                <p>Lieu d'arrivé</p>
            </div>
            <div class="trajet">
                <p>Date de départ</p>
                <p>Heure de départ</p>
            </div>
        </div>
    </div>
    <hr>
    <div class="passager">
        <p>Passager</p>
        <table>
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Prénom</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Koffi</td>
                    <td>Elisee</td> 
            </tbody>
        </table>
    </div>
    <div class="detail">
        <p>Notes : </p>
        <div class="sous">
            <p>Sous-total</p>
            <p>prix</p>
        </div>
    
        <hr>
        <div class="sous">
            <p>Total</p>
            <p>prix</p>
        </div>
    </div>
    
    <div id="popup">
        <div class="content">
            <h2>Ajouté un Nouveau Vehicule</h2>
            <hr>
            <h3>Numero de réservation</h3>
            <p>123456</p>
            <h3>Total</h3>
            <p>23456f</p>
        </div>
        <a class="fas fa-times close" onclick="popupToggle();"></a>
        <div class="save">
            <a href="{% url 'appbilletterie:valider_paiement' %}"><input type="button" value="Enregistrer"></a>
        </div>
    </div>



    <script src="{% static 'javaScript/paiement.js' %}"></script>
</body>
</html>

billetterie/templates/htmlPages/reservation.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reservez vos tickets ici</title>
    <link rel="stylesheet" href="{% static 'cssPages/reservation.css' %}">
    <link rel="stylesheet" href="{% static 'font/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'font/css/fontawesome.min.css' %}">

</head>
<body>
    <section>
        
        <div id="popup">
            <div>
                <button class="add_new button"><i class="fas fa-chevron-left"></i><a href="{% url 'appbilletterie:index' %}"> Retour</a></button>
            </div>
            <div class="content">
                <h2>Créer une Commande</h2>
                {% for message in messages %}
                <p class="bg-info">{{message}}</p>
                {%endfor%}
                <hr>
                <form action="" method="post">
                    <div>
                        {% for  error in errors %}
                        {{error}}
                        {%endfor%}
                    </div>
                    {% csrf_token %}
                    <!-- <p>Sejour</p>
                    <input type="text" name="#" placeholder="Allez simple ou Allé-retour"> -->
                    <div class="lieu">
                        <div class="lieu1">
                            <p>Trajet</p>
                           
                            <select name="trajet" required>
                                {% for trajet in trajets %}
                                <option value="{{trajet.id}}">  {{trajet.lieu_depart}}- {{trajet.lieu_arrivee}}</option>
                                  {%endfor%}
                                <option value="korhogo">Korhogo</option>
                            </select> 
                        </div>
                        <!-- <div class="lieu1">
                            <p>Arrivé</p>
                            <select name="#" required>
                                {% for trajet in trajets %}
                            <option value="{{trajet.id}}"> </option>
                              {%endfor%}
                            </select> 
                        </div> -->
                    </div>
                    <div class="heure">
                        <div class="heure1">
                            <p>Date de Depart</p>
                            <input type="date" name="date_depat">
                        </div>
                        <!-- <div class="heure1">
                            <p>Date de Retour</p>
                            <input type="date" name="#">
                        </div> -->
                    </div>
                    <div class="voiture_prix">
                        <!-- <div class="voiture_prix1">
                            <p>Passagers</p>
                            <input type="number" name="#" placeholder="nombre de Passager">
                        </div> -->
                        <div class="voiture_prix1">
                            <p>Heure de Depart</p>
                            <input type="time" name="heure_depat">
                        </div>
                    </div>
                    <button type="submit" class="add_new button"></i>Reserver</button> 
                   
                    <!-- <button class="add_new button"><i class="fas fa-search"></i><a href="{% url 'appbilletterie:search' %}" style="color: #fff; padding: 13px 5px;"> Recherche</a></button> -->
                </form>
            </div>
        </div>
    </section>
    
    <!-- END section -->
    <script src="{% static 'adminPanel/dash_js/gestion.js' %}"></script>
</body>
</html>

billetterie/templates/htmlPages/search.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recherche Trajet</title>
    <link rel="stylesheet" href="{% static 'cssPages/search.css' %}">
    <link rel="stylesheet" href="{% static 'font/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'font/css/fontawesome.min.css' %}">
    <script src="{% static 'qrcodejs/qrcode.min.js' %}"></script>

</head>
<body>
    <style>
@media print {
  .print-btn { display: none; }
  thead { display: table-header-group; position: fixed; top: 0; }
}


    </style>
    <div class="table">
        <div class="table_header">
            <p>Trajet</p>
            <div>
                <button class="add_new button"><i class="fas fa-chevron-left"></i><a href="{% url 'appbilletterie:index' %}"> Retour</a></button>
            </div>
        </div>
        <hr>
        <p>Trajet</p>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Client</th>
                    <th>Statut</th>
                    <th>Trajet</th>
                    <th>Siège</th>
                    <th>Date de depart</th>
                    <th>Heure de depart</th>
                    <th>Qr Code</th>
                </tr>
            </thead>
            <tbody>
                {% for reservation in reservations %}
                <tr>
                    <td>{{reservation.id}}</td>
                    <td>{{reservation.client.username}}</td>
                    <td>{% if reservation.status %}Confirmée{%endif%}</td>
                    <td>{{reservation.trajet.lieu_depart}}-{{reservation.trajet.lieu_arrivee}}</td>
                    <td>{{reservation.place}}</td>
                    <td>{{reservation.date_depat}}</td>
                    <td>{{reservation.heure_depat}}</td>
                    <td>
                        <div class="qr-code"></div>
                        <button class="print-btn"><i class="fas fa-print"></i></button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
                
                
                
        </table>
    </div>
    
    <div class="para"></div>

    <!-- <div class="champ">
        <table>
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Email</th>
                    <th>Téléphone</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><input type="text" name="#"></td>
                    <td><input type="text" name="#"></td>
                    <td><input type="email" name="#"></td>
                    <td><input type="tel" name="#"></td>   
            </tbody>
        </table>
        <br>
    </div> -->

    <p class="notes">Notes</p>
    <textarea name="#" placeholder="Je souhaite svp une place à l'avant"></textarea>
    <hr>

    <div class="valider">
        <a href="{% url 'appbilletterie:paiement' %}"><input type="button" value="Envoyer"></a>
    </div>



    <script>



// Sélectionnez tous les conteneurs de code QR et parcourez-les
const qrContainers = document.querySelectorAll('.qr-code');
qrContainers.forEach(qrContainer => {
    // Récupérez l'ID de réservation de la ligne de réservation correspondante
    const id = qrContainer.parentNode.parentNode.children[0].textContent;

    // Générez le code QR avec l'ID de réservation
    const qrCode = new QRCode(qrContainer, {
        text: id,
        width: 128,
        height: 128,
        colorDark: "#000000",
        colorLight: "#ffffff",
        correctLevel: QRCode.CorrectLevel.H
    });
});




const printBtns = document.querySelectorAll('.print-btn');
printBtns.forEach(printBtn => {
  printBtn.addEventListener('click', event => {
    const row = event.target.closest('tr');
    const table = row.closest('table');
    const headerRow = table.querySelector('thead tr');
    const tableRows = table.querySelectorAll('tbody tr');
    const rowIdx = Array.from(tableRows).indexOf(row);
    // Create a new HTML document to print the row
    const printWindow = window.open('', 'Print', 'height=600,width=800');
    printWindow.document.write(`
      <html>
        <head>
          <title>Print</title>
          <style>
            @media print {
              body * {
                visibility: hidden;
              }
              #print-content, #print-content * {
                visibility: visible;
              }
              #print-content {
                position: absolute;
                left: 0;
                top: 0;
              }
            }
          </style>
        </head>
        <body>
          <div id="print-content">
            <table>
              <thead>
                ${headerRow.outerHTML}
              </thead>
              <tbody>
                ${tableRows[rowIdx].outerHTML}
              </tbody>
            </table>
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
    printWindow.close();
  });
});


    </script>


    
    
</body>
</html>

billetterie/templates/htmlPages/valider_paiement.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Valider le paiement</title>
    <link rel="stylesheet" href="{% static 'cssPages/search.css' %}">
    <link rel="stylesheet" href="{% static 'font/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'font/css/fontawesome.min.css' %}">
</head>
<body>
    
    <div class="container">
        <div class="table_header">
            <p>Numero reservation</p>
            <div>
                <button class="add_new button"><i class="fas fa-chevron-left"></i><a href="{% url 'paiement' %}"> Retour</a></button>
            </div>
        </div>
        <hr>
        <div class="info-trajet">
            <div class="infos">
                <div class="info">
                    <p class="p">Statut</p>
                    <p><input type="text" name="#" placeholder=""></p>
                </div>
                <div class="info">
                    <p class="p">Statut</p>
                    <p><input type="text" name="#" placeholder=""></p>
                </div>
            </div>
            <div class="information">
                <div class="info">
                    <p class="p">Nom</p>
                    <p><input type="text" name="#" placeholder=""></p>
                </div>
                <div class="info">
                    <p class="p">Prenom</p>
                    <p><input type="text" name="#" placeholder=""></p>
                </div>
            </div>
            <div class="trajets">
                <div class="trajet">
                    <p class="p">Email</p>
                    <p><input type="text" name="#" placeholder=""></p>
                </div>
                <div class="trajet">
                    <p class="p">Téléphone</p>
                    <p><input type="text" name="#" placeholder=""></p>
                </div>
            </div>
        </div>
        <div class="espace"></div>
        <hr>
        <table>
            <thead>
                <tr>
                    <th>Lieu de départ</th>
                    <th>Lieu d'arrivé</th>
                    <th>Date de départ</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Abengourou</td>
                    <td>Abidjan</td>
                    <td>Dim, 03 Dec 2022 - 08h30</td> 
            </tbody>
        </table>
        <div class="espace"></div>
        <h1>INFORMATION PASSAGER</h1>
        <hr>
        <div class="infotrajets">
            <div class="trajet">
                <p class="p">Nom</p>
                <p><input type="text" name="#" placeholder=""></p>
            </div>
            <div class="trajet">
                <p class="p">Prénom</p>
                <p><input type="text" name="#" placeholder=""></p>
            </div>
            <div class="trajet">
                <p class="p">Téléphone</p>
                <p><input type="tel" name="#" placeholder=""></p>
            </div>
        </div>
        <div class="espace"></div>  
        <div class="valider val">
            <a href="#"><input type="button" value="Valider"></a>
        </div>
    </div>

</body>
</html>